import type { ShoppingItem } from "@/types";

export const SHOPPING_ITEMS: ShoppingItem[] = [
  { id: "001", name: "Indomie", completed: false },
  { id: "002", name: "Milk", completed: false },
  { id: "003", name: "Milo", completed: false },
  { id: "004", name: "Sugar", completed: false },
  { id: "005", name: "Spagetti", completed: false },
  { id: "006", name: "Maggi [know/star]", completed: false },
  { id: "007", name: "Pepper", completed: false },
  { id: "008", name: "Tomato", completed: false },
  { id: "009", name: "Cream", completed: false },
  { id: "010", name: "Deodorant", completed: false },
  { id: "011", name: "Oats", completed: false },
  { id: "012", name: "Cornflakes", completed: false },
  { id: "013", name: "Sweets", completed: false },
  { id: "014", name: "Chewing gum", completed: false },
  { id: "015", name: "Biscuits", completed: false },
  { id: "016", name: "Fleets", completed: false },
  { id: "017", name: "Air freshner", completed: false },
  { id: "018", name: "Cacatin", completed: false },
  { id: "019", name: "Relaxer", completed: false },
  { id: "020", name: "Custard", completed: false },
  { id: "021", name: "Paracetamol", completed: false },
  { id: "022", name: "Tissue", completed: false },
  { id: "023", name: "Detergents", completed: false },
  { id: "024", name: "Dudu osun", completed: false },
  { id: "025", name: "Pen, Pencil [Blue & Red]", completed: false },
  { id: "026", name: "Aloe Vera & Face wash", completed: false },
  { id: "027", name: "Haemoglobin 12 & Blood Tonic", completed: false },
  { id: "028", name: "Pad", completed: false },
  { id: "029", name: "Toothpaste", completed: false },
  { id: "030", name: "Rice", completed: false },
  { id: "031", name: "Butter", completed: false },
  { id: "032", name: "Red oil", completed: false },
  { id: "033", name: "Groundnut oil", completed: false },
  { id: "034", name: "Groundnut oil", completed: false },
  { id: "035", name: "Earpod", completed: false },
  { id: "036", name: "Waste nylon", completed: false },
  { id: "037", name: "Edge control", completed: false },
  { id: "038", name: "Plantain", completed: false },
  { id: "039", name: "Garri", completed: false },
  { id: "040", name: "Beans", completed: false },
  { id: "041", name: "Potato chips", completed: false },
  { id: "042", name: "Lipton", completed: false },
  { id: "043", name: "Wipers", completed: false },
  { id: "044", name: "Morning Fresh", completed: false },
  { id: "045", name: "Lipton", completed: false },
];
